##spring##
spring:
  application:
    name: app-server-eureka

##server##
server:
  port: 8090

##eureka##
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
    register-with-eureka: false
    fetch-registry: false