##server##
server:
  port: 8091

##spring##
spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

##eureka##
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/

##management##
management:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
