##server##
server:
  port: 8082

##spring##
spring:
  application:
    name: app-server-domain-order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

##management##
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"